# Generated by Django 3.2 on 2021-05-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20210507_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='guest',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2021-08-14'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
    ]
